<?php

namespace AppBundle\Repository;

/**
 * LessonCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LessonCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
